fixing error : RuntimeError
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation
Fix as suggested by the author of the code  WongKinYiu